### PR TITLE
Update of dependencies

### PR DESCRIPTION
**Pull request by MassiveHiggsField**
This should pretty much fix/add everything from https://github.com/jonjomckay/quahog/issues/15

### CODE REVIEW

**Comment by MassiveHiggsField** [comment]
I've made a pr with everything needed for this. But since i changed the namespaces to make them more composer friendly, this is a bc breaking change, so this fix should get a new major version.

**Comment by jonjomckay** [comment]
Thanks for this PR - what do you think of changing the vendor name in the namespace to `Xenolope` instead of `Blurgroup`? It's what I normally release my "personal" packages under, and I haven't had any affiliation with blur Group for over 2 years now!

**Comment by MassiveHiggsField** [comment]
I changed the namespace but you should probably rename the package on packagist and update the composer.json and readme too.

**Comment by jonjomckay** [comment]
@MassiveHiggsField oops, could you also update README.md with the new namespace?

**Comment by MassiveHiggsField** [comment]
You already merged it, but i started a new pr https://github.com/jonjomckay/quahog/pull/17

**Pull request merged**
